# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import parsing
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(300, 175)
        MainWindow.setMinimumSize(QtCore.QSize(300, 175))
        font = QtGui.QFont()
        font.setFamily("Caveat")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Status_Weather = QtWidgets.QLabel(self.centralwidget)
        self.Status_Weather.setGeometry(QtCore.QRect(110, 100, 91, 30))
        font = QtGui.QFont()
        font.setFamily("Caveat")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Status_Weather.setFont(font)
        self.Status_Weather.setObjectName("Status_Weather")
        self.ButtonReset = QtWidgets.QPushButton(self.centralwidget)
        self.ButtonReset.setGeometry(QtCore.QRect(202, 0, 101, 28))
        self.ButtonReset.setObjectName("ButtonReset")
        self.Temper = QtWidgets.QLabel(self.centralwidget)
        self.Temper.setGeometry(QtCore.QRect(100, 40, 100, 65))
        self.Temper.setObjectName("Temper")
        self.SpeedWind = QtWidgets.QLabel(self.centralwidget)
        self.SpeedWind.setGeometry(QtCore.QRect(10, 120, 81, 16))
        self.SpeedWind.setObjectName("SpeedWind")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.reset()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Status_Weather.setText(_translate("MainWindow", "TextLabel"))
        self.ButtonReset.setText(_translate("MainWindow", "PushButton"))
        self.Temper.setText(_translate("MainWindow", "TextLabel"))
        self.SpeedWind.setText(_translate("MainWindow", "TextLabel"))

    def reset(self):
        self.ButtonReset.clicked.connect(self.update)

    def update(self):
        parsing.parsing.chec_connection()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
